### ISSUE TITLE
Please add auto connect on startup

### ISSUE THREAD

**Issue by mawa85** [ykasidit/libbluetooth_gnss#3]
Could you add Auto-Connect on Startup of the application?
Would really help to automate the connection with Tasker etc...

**Comment by ykasidit** [comment]
Hello, this was added by @auricgoldfinger into the app project - should be released into the next release: https://github.com/ykasidit/bluetooth_gnss/pull/3/commits/b77c2bcf3345caa2e9c503186e9b2751aec929c0
