### ISSUE TITLE
Please add https support for NTRIP

### ISSUE THREAD

**Issue by jensMF** [ykasidit/libbluetooth_gnss#4]
Hi,

the NTRIP provider I use (https://euref-ip.net/home) states that port 2101 and 80 are deprecated (see here: https://register.rtcm-ntrip.org/cgi-bin/registration.cgi citation: " ... All our Broadcasters are accessible through ports 2101 and 80 (deprecated) as well as port 443 (TLS). ...")
So it would be nice to have TLS support.

Just if you have time. Thank you :-)

**Comment by ykasidit** [comment]
Hello,
This feature is now implemented. Tested with "ntrip.data.gnss.ga.gov.au" port 443. Please kindly try the new release apk: https://github.com/ykasidit/bluetooth_gnss/releases/tag/v1.0.26

**Comment by jensMF** [comment]
Thank you, it works for me.
